### ISSUE TITLE
Cannot save if no or just 1 job_posting_answer

### ISSUE THREAD

**Issue by peterj35** [RobertWSaunders/engsoc-dash#26]
Currently, if there are no job posting questions, if someone tries to apply to that job, there will be a undefined method error for each param["answers"] class, because there won't be any answers passed in, breaking the logic

to fix, must check if params.has_key?("answers"), then perform a simple redirect to finalize job application if answers param doesn't exist

the issue is, how to logically find out the job application id for the redirect if no params are passed in from the form? 

either:
- forgo the question & answering pages if there's no questions for job post
- pass in job_application_id from the answers page

**Comment by peterj35** [comment]
Wrote logic for just 1 jpa


```ruby
# POST /job_posting/:job_posting_id/job_application/:job_application_id/job_posting_answers
  def create
    if params.has_key?("answer")
      @answer = JobPostingAnswer.create(answer_params(params["answer"]))
    else
      params["answers"].each do |key, answer|
        @answer = JobPostingAnswer.create(answer_params(answer))
      end
    end
    @job_application_id = @answer.job_application_id
    redirect_to finalize_job_application_path(:id => @job_application_id)
  end
```

still need to handle logic for no jpa

**Comment by RobertWSaunders** [comment]
This has gone stale, going to do a system wide audit soon.
