### ISSUE TITLE
Sort/Organize Functionality of Organization jobs

### ISSUE THREAD

**Issue by peterj35** [RobertWSaunders/engsoc-dash#38]
Currently, jobs sort based on whether they are managerial positions or not

But aside from that, no sort/organization feature for regular positions

Some organizations have "Head of ____" positions, which should ideally be at the top of the org job list

So allow managers to sort manually how jobs should position themselves

**Comment by RobertWSaunders** [comment]
This has gone stale, going to do a system wide audit soon.
