### ISSUE TITLE
Make error message formats consistent between scaffolded & complex validation errors

### ISSUE THREAD

**Issue by peterj35** [RobertWSaunders/engsoc-dash#39]
For validation error displaying for more complex objects (where params need to be passed in, ie. creating job postings), currently using a combination of html_safe flash messages and redirect_to, instead of the more traditional (scaffolded) passing in native object errors and render.

Therefore the appearance of validation error messages are slightly different:

scaffolded (ie. organization):
![image](https://cloud.githubusercontent.com/assets/6766177/25736108/d05422e4-31aa-11e7-8734-5a5ca24fd266.png)

complex (ie. job_posting):
![image](https://cloud.githubusercontent.com/assets/6766177/25736123/e121ee30-31aa-11e7-9221-b80c24932232.png)

So for complex errors, error messages should be changed to be the same format as the scaffolded error messages.

**Comment by peterj35** [comment]
Note that not only the wording format must be changed, but also that the non-flash error messages are displayed within the card-body

**Comment by RobertWSaunders** [comment]
This has gone stale, going to do a system wide audit soon.
