### ISSUE TITLE
When creating a job post for a job, the title of the job post cannot be set manually (to be different than the jp's job title)

### ISSUE THREAD

**Issue by peterj35** [RobertWSaunders/engsoc-dash#45]
sets the title as the jp's job title with disregard to user input in the new jp page. either:
- not allow the option to adjust the title of the jp
or
- correct this to properly pass in the jp title in the new jp form as a param for creating the jp

**Comment by peterj35** [comment]
this behaviour leads to the failure of the test case:
`      it "shows open postings for active organizations" do
        expect(response.body).to have_content(@open_jp_active_org.title)
      end`

because the factory sets a different name for the jp, which is not saved and therefore not rendered

**Comment by RobertWSaunders** [comment]
This has gone stale, going to do a system wide audit soon.
