### ISSUE TITLE
Have one position be a part of multiple organizations

### ISSUE THREAD

**Issue by CarsonCook** [RobertWSaunders/engsoc-dash#76]
For example, Tea Room and Clark Hall Pub would have their own organizations - they are different entities and you don't want a tea room manager seeing applications to clark.

But, the Director of services needs to have managerial access to both Tea Room and Clark organizations. You don't want the DoS to have admin access though, as that would give them access to non-service organizations.

I think the solution is when creating an organization, having the ability to add a manager job from other organizations as a manager job for the organization being made - you don't want to have to make 2 DoS jobs (one for Tea, one for Clark) and manually hire the same DoS for both.

This also makes sense as then you could have an Executive-Director Organization that posts the DoS job and hires it, and then DoS is automatically within Tea Room, Clark etc. organizations

**Comment by RobertWSaunders** [comment]
This is an interesting feature, will add this as a new feature request using the template. Closing for now.
