### ISSUE TITLE
Interview time email failing to send

### ISSUE THREAD

**Issue by maxkaran** [RobertWSaunders/engsoc-dash#79]
## Description
"I’m trying to schedule interviews for this week. I got 13/23 applicants scheduled with no issues but now I’m receiving the following error. The address I’m at is https://dash.engsoc.queensu.ca/interviews/manage. I’ve tried logging in and out with no luck."

User cannot send scheduling emails, or reschedule interviews. Was logged in as 16msm1@queensu.ca and doing hiring on behalf of the Queen's Engineering Competition. Problem exists for a handful of users.

### Expected Behavior
Should send a confirmation email to the applicant

### Actual Behavior
![image](https://user-images.githubusercontent.com/32376872/46037653-c080c900-c0d6-11e8-81b8-747a81c0ca13.png)

### Steps to Reproduce

1. Login as manager of QEC, got to https://dash.engsoc.queensu.ca/interviews/manage

2. Attempt to schedule an email for some users.

**Comment by RobertWSaunders** [comment]
Will give this a look over thanksgiving!
